logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    com.example.demo.controller: INFO
  file:
    name: logs/application-debug.log